### ISSUE TITLE
Run an evaluation locally (Step 4) fail 

### ISSUE THREAD

**Issue by LianwMS** [Azure-Samples/assistant-data-openai-python-promptflow#19]
(.venv) PS D:\aigallery\assistant-data-openai-python-promptflow> python ./src/evaluate.py --evaluation-name assistant-dev --evaluation-data-path ./data/ground_truth.jsonl --metrics similarity
D:\aigallery\assistant-data-openai-python-promptflow\.env
2024-05-13 09:35:57,062 - root - INFO - Running script with arguments: Namespace(evaluation_data_path='./data/ground_truth.jsonl', evaluation_name='assistant-dev', evaluation_endpoint='https://aoai-yi3gbdb7acyn6.openai.azure.com/', evaluation_model='gpt-35-turbo', metrics=['similarity'])
2024-05-13 09:35:57,063 - root - INFO - Using Azure AD authentification [recommended]
2024-05-13 09:35:58,738 - root - INFO - Running evaluation name=assistant-dev on dataset ./data/ground_truth.jsonl
Traceback (most recent call last):
  File "D:\aigallery\assistant-data-openai-python-promptflow\src\evaluate.py", line 227, in <module>
    main()
  File "D:\aigallery\assistant-data-openai-python-promptflow\src\evaluate.py", line 212, in main
    result, tabular_result = run_evaluation(
                             ^^^^^^^^^^^^^^^
  File "D:\aigallery\assistant-data-openai-python-promptflow\src\evaluate.py", line 135, in run_evaluation
    result = evaluate(
             ^^^^^^^^^
  File "D:\aigallery\assistant-data-openai-python-promptflow\.venv\Lib\site-packages\promptflow\evals\evaluate\_evaluate.py", line 100, in evaluate
    _validation(target, data, evaluators, output_path, tracking_uri, evaluation_name)
  File "D:\aigallery\assistant-data-openai-python-promptflow\.venv\Lib\site-packages\promptflow\evals\evaluate\_evaluate.py", line 67, in _validation
    _validate_input_data_for_evaluator(evaluator, evaluator_name, data_df)
  File "D:\aigallery\assistant-data-openai-python-promptflow\.venv\Lib\site-packages\promptflow\evals\evaluate\_evaluate.py", line 30, in _validate_input_data_for_evaluator
    raise ValueError(f"Missing required inputs for evaluator {evaluator_name} : {missing_inputs}.")
ValueError: Missing required inputs for evaluator similarity : ['question', 'answer'].

**Comment by jfomhover** [comment]
This now works e2e
